In [1]:
import nltk
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix
import itertools
import matplotlib.pyplot as plt
from sklearn.pipeline import Pipeline
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
from yellowbrick.features.manifold import Manifold
import yellowbrick as yb

In [2]:
data = open("apple.txt").read().splitlines()

In [3]:
data

['From: Apple Inc. - Izolda Jablonska <reply@unpogina.info>',
 'Subject: Nice to meet you, Agnieszka',
 'Hello Agnieszka,',
 'Congratulations to all of our recent winners of the Apple smartphone competition.',
 'Apple offered you a chance to win the latest iPhone - one of the most popular and best smartphones of the moment.',
 'No wonder that we have received thousands of applications, including yours! IPhone XS winner this week is ... Agnieszka Malankiewicz',
 'Congratulations, Agnieszka,',
 'Receive your iPhone XS!']

In [4]:
# Import the libraries we need
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

# Step 2. Design the Vocabulary
# The default token pattern removes tokens of a single character. That's why we don't have the "I" and "s" tokens in the output
count_vectorizer = CountVectorizer()

# Step 3. Create the Bag-of-Words Model
bag_of_words = count_vectorizer.fit_transform(data)

# Show the Bag-of-Words Model as a pandas DataFrame
feature_names = count_vectorizer.get_feature_names()
pd.DataFrame(bag_of_words.toarray(), columns = feature_names)

,agnieszka,all,and,apple,applications,best,chance,competition,congratulations,from,...,we,week,win,winner,winners,wonder,xs,you,your,yours
0,0,0,0,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,1,0,1,0,0,0,1,1,0,...,0,0,0,0,1,0,0,0,0,0
4,0,0,1,1,0,1,1,0,0,0,...,0,0,1,0,0,0,0,1,0,0
5,1,0,0,0,1,0,0,0,0,0,...,1,1,0,1,0,1,1,0,0,1
6,1,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0

In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

tfidf_vectorizer = TfidfVectorizer()
values = tfidf_vectorizer.fit_transform(data)

# Show the Model as a pandas DataFrame
feature_names = tfidf_vectorizer.get_feature_names()
pd.DataFrame(values.toarray(), columns = feature_names)

,agnieszka,all,and,apple,applications,best,chance,competition,congratulations,from,...,we,week,win,winner,winners,wonder,xs,you,your,yours
0,0.000000,0.00000,0.000000,0.263668,0.000000,0.000000,0.000000,0.00000,0.000000,0.36459,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
1,0.294764,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.389596,0.000000,0.000000
2,0.535502,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
3,0.000000,0.30798,0.000000,0.222729,0.000000,0.000000,0.000000,0.30798,0.258111,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.30798,0.000000,0.000000,0.000000,0.000000,0.000000
4,0.000000,0.00000,0.214745,0.155302,0.000000,0.214745,0.214745,0.00000,0.000000,0.00000,...,0.000000,0.000000,0.214745,0.000000,0.00000,0.000000,0.000000,0.179973,0.000000,0.000000
5,0.153111,0.00000,0.000000,0.000000,0.241469,0.000000,0.000000,0.00000,0.000000,0.00000,...,0.241469,0.241469,0.000000,0.241469,0.00000,0.241469,0.202370,0.000000,0.000000,0.241469
6,0.603358,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.797471,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
7,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.466653,0.000000,0.556813,0.000000